# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dwarf
email: yngvarr@the-dwarf.ru
description: > # this means to ignore newlines until "baseurl:"
    Потому что быть дварфом - офигительно!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://the-dwarf.ru" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: GIRAFF 

# Build settings
markdown: kramdown
timezone: Asia/Novosibirsk
encoding: UTF-8

relative_permalinks: false
permalink: /posts/:title
future: false
